SCRUM-3644: Reorder logic for filters
alliance-genome/agr_ui pull request #1247
Opened 2024-01-29 12:56 UTC by abecerra

2024-01-29 14:44 UTC, adamgibs approved these changes

2024-01-29 14:46 UTC, oblodgett requested changes
Has this been tested on all Data Tables on the site?

2024-01-29 14:46 UTC, oblodgett commented on src/components/dataTable/DataTable.js
> -  if (isLoading || isFetching) {
I believe you want the isFetching because when they hit the second page this needs to turn on.

2024-01-30 14:08 UTC, abecerra commented
@oblodgett: without the `isFetching`, the pagination+filter issue is solved. I am not sure why 
I tested in the gene and disease pages (with the disease ribbon)

2024-01-30 15:29 UTC, oblodgett commented
We need to have the isFetching so somewhere there we need to fix it... this need to not be a hack fix

2024-01-30 17:01 UTC, oblodgett approved these changes

2024-01-30 17:01 UTC, merged